[features]
seeds = false
skip-lint = false

[programs.localnet]
solstreams = "strMZGgbP9ZSv61K14burRv5LnWmb1YDTuvjyJK5KVV"

[programs.devnet]
solstreams = "strMZGgbP9ZSv61K14burRv5LnWmb1YDTuvjyJK5KVV"

[programs.mainnet]
solstreams = "strMZGgbP9ZSv61K14burRv5LnWmb1YDTuvjyJK5KVV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id_1.json"

[scripts]
build_sdk = "yarn run build:sdk"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
