[features]
seeds = false
skip-lint = false

[programs.localnet]
solstreams = "STRMsoUj1u6oEhDaG6gtECiixy5fKm1sNAyALaUhSBo"

[programs.devnet]
solstreams = "STRMsoUj1u6oEhDaG6gtECiixy5fKm1sNAyALaUhSBo"

[programs.testnet]
solstreams = "STRMsoUj1u6oEhDaG6gtECiixy5fKm1sNAyALaUhSBo"

[programs.mainnet]
solstreams = "STRMsoUj1u6oEhDaG6gtECiixy5fKm1sNAyALaUhSBo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build_sdk = "pnpm run build:sdk"
test = "pnpm run test"
