name: 'Build and test program'

on:
  push:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/anchor-install
      - uses: ./.github/actions/npm-install
      - run: anchor build
      - run: pnpm run build:sdk
      - run: pnpm run test