name: 'Build and test program'

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Solana Anchor build'
        uses: metadaoproject/setup-anchor@v1.1
        with:
          anchor-version: '0.26.0'
          solana-cli-version: '1.16.0'
          node-version: '18.0.0'
      - run: yarn
        shell: bash
      - run: anchor build
        shell: bash
      - run: anchor test --provider.wallet THIS_IS_A_TEST_KEY.json --skip-build
        shell: bash
